id: P005395
initial_creation_type: ocr
created_at: 21/03/2020
last_modified_at: 2021-12-17 11:48:08.377028
source_metadata:
  id: bdr:W1KG5900
  title: ཏུན་ཧོང་ནས་ཐོན་པའི་གནའ་བོའི་བོད་ཡིག་ཤོག་དྲིལ་།
  author: ''
  volumes:
    f22f1c684e0a465ca8ee23a85f6b9fc4:
      image_group_id: I1KG5919
      title: ''
      volume_number: 1
      total_pages: 336
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
